spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_optimize}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} // will be off in prod because of control issue (Use Flyway Tools)
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        default_batch_fetch_size: 10   // batch fetch optimization