CREATE TABLE inventory
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    product_id BIGINT,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);

ALTER TABLE inventory
    ADD CONSTRAINT FK_INVENTORY_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

